package dev.nkap.server.payment;

import dev.nkap.core.money.Money;
import dev.nkap.core.payment.ReferenceId;
import dev.nkap.provider.Capability;
import dev.nkap.provider.PaymentIntent;
import dev.nkap.provider.ProviderAdapter;
import dev.nkap.server.provider.AdapterRegistry;
import dev.nkap.server.provider.PublicBaseUrl;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Turns a validated refund request into a new {@code DISBURSE} payment, reserved against
 * the collection it refunds before the operator is ever asked (issue #84, ADR 0010).
 *
 * <p>{@code RefundController} has already checked the rules that do not depend on
 * concurrency — the original is a {@code SUCCEEDED} collection belonging to this merchant,
 * the amount is positive, and {@code original.reserveRefund} (a courtesy check against the
 * controller's own unlocked read) has already rejected the common case of an amount that
 * obviously exceeds what remains. What is left here is the one check that <strong>does</strong>
 * depend on concurrency: two refunds for the same collection, issued at once, must not both
 * pass. That is {@link PaymentRepository#reserveRefund} — a single atomic
 * {@code UPDATE … SET refunded_minor = refunded_minor + ?}, refused at commit by the
 * database's own {@code CHECK} (V8) — never a read-decide-write taken under an explicit lock
 * in this class. See its javadoc, and {@code Payment.reserveRefund}'s, for why that
 * distinction is the entire point of this correction.
 *
 * <p>The reservation and the new refund row are persisted in <strong>one transaction</strong>,
 * so a crash between the two would never leave a reservation with no payment behind it, or a
 * refund payment with no reservation counted against it. The adapter is resolved
 * <strong>before</strong> that transaction opens, for the same reason
 * {@link PaymentService#createAndSubmit} resolves it before persisting anything.
 *
 * <p><strong>This class cannot promise "throws only before anything is persisted" the way
 * {@code createAndSubmit} does</strong> — {@code RefundController} does not assume it can.
 * The reservation transaction commits, and only then is the operator ever asked
 * ({@link PaymentService#submit}, the same method {@code createAndSubmit} uses, called for a
 * payment this class persisted itself). If that second step throws, or the process is killed
 * before it finishes, the refund is real and stranded in {@code CREATED} — the controller
 * checks for exactly that before deciding whether to abandon its idempotency claim, and
 * {@code Reconciler} sweeps a refund left that way past a grace period (issue #84's second
 * correction).
 */
@Service
public class RefundService {

    private final PaymentRepository payments;
    private final AdapterRegistry adapters;
    private final PaymentService paymentService;
    private final PublicBaseUrl publicBaseUrl;
    private final TransactionTemplate tx;

    public RefundService(PaymentRepository payments, AdapterRegistry adapters, PaymentService paymentService,
                         PublicBaseUrl publicBaseUrl, PlatformTransactionManager txManager) {
        this.payments = payments;
        this.adapters = adapters;
        this.paymentService = paymentService;
        this.publicBaseUrl = publicBaseUrl;
        this.tx = new TransactionTemplate(txManager);
    }

    /**
     * Reserves {@code amount} against {@code original} and submits the refund, under
     * {@code refundReference} — generated by the caller, not here, so it can still identify
     * this refund even if this call throws after the reservation transaction already
     * committed. Returns the refund in whichever state the submission left it —
     * {@code SUBMITTED} / {@code PENDING} on acknowledgement, {@code FAILED} on an outright
     * refusal, {@code UNKNOWN} on no answer — exactly the same possibilities
     * {@code createAndSubmit} documents, because this is that same call.
     *
     * <p>Throws {@link RefundExceedsRemainingException} if a concurrent refund already spent
     * the amount {@code original} had left — rare, since the controller's own courtesy check
     * already refused the common case, but not impossible, and this is the one that is
     * actually authoritative. Persists nothing when it does.
     *
     * @param note the payer- and payee-facing message MTN is sent with the transfer
     */
    public Payment createAndSubmit(Payment original, Money amount, String note, ReferenceId refundReference) {
        ProviderAdapter adapter = adapters.require(original.provider());
        ReferenceId originalReference = original.reference();

        tx.executeWithoutResult(status -> {
            // The atomic UPDATE, not a lock taken here, is what refuses a concurrent
            // over-refund — see the class javadoc.
            payments.reserveRefund(originalReference, amount);

            PaymentIntent refundIntent = new PaymentIntent(Capability.Operation.DISBURSE, amount,
                    original.intent().counterpartyMsisdn(), note, note,
                    publicBaseUrl.providerOptionsFor(original.provider(), refundReference));
            Payment refund = Payment.createRefund(refundReference, original.provider(), original.merchantId(),
                    refundIntent, originalReference);
            // Which endpoint this refund is actually being submitted to, from configuration,
            // before the operator is ever called (issue #122) — the same installation the
            // original collection used, since a refund is submitted through original.provider().
            adapters.settlementEndpoint(original.provider()).ifPresent(refund::recordProviderBaseUrl);
            payments.save(refund);
        });

        Payment refund = payments.findByReference(refundReference).orElseThrow();
        // The reference as a structured field, matching PaymentService.createAndSubmit and
        // SettlementService — one refund's story, filterable across all three (issue #75).
        try (var ignored = MDC.putCloseable("reference", refundReference.toString())) {
            return paymentService.submit(adapter, refund.intent(), refundReference);
        }
    }
}
